export const googleFonts = [
  'Roboto',
  'Open Sans',
  'Lato',
  'Oswald',
  'Slabo 27px',
  'Roboto Condensed',
  'Monsterrat',
  'Source Sans Pro',
  'Raleway',
  'PT Sans',
  'Playfair Display',
  'Bitter',
  'Libre Baskerville',
  'Archivo Narrow',
  'Alegreya Sans',
  'Ubuntu',
  'Crimson Text',
  'Heebo',
  'Cabin',
  'Lobster',
  'Inter',
];
